version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db    
      - redis  
    networks:
      - fullstack

  db:
    container_name: full_db_postgres
    image: postgres
    restart: always
    volumes:
      - database_postgres:/usr/local/var/postgres/data
    ports:
      - "${DBPORT}:${DBPORT}"
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
    networks:
      - fullstack

  redis:
    image: redis
    container_name: redis
    ports: ["6379:6379"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf
    networks:
      - fullstack

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "app"
    networks:
      - fullstack
    # volumes:
    #   - ./nginx/nginx.conf:/usr/local/etc/nginx/nginx.conf

volumes:
  api:
  database_postgres:    
  redis:      
  nginx:       

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
