version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db    
      - redis    
    networks:
      - fullstack


  db:
    container_name: full_db_postgres
    image: postgres
    volumes:
      - database_postgres:/usr/local/var/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_cyber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis
    container_name: redis
    ports: ["6379:6379"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf

volumes:
  api:
  database_postgres:    
  redis:             

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
